name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install libgi
      run: sudo apt install libgirepository1.0-dev

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make
